### ISSUE TITLE
Deprecate or delete this repository?

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/hyrax-on-wings#13]
I believe this repository was only used during the polar vortex sprint at PSU and hasn't seen any work in the past 11 months.  With wings work continuing in hyrax proper, can this repository be deprecated or better yet deleted?

**Comment by no-reply** [comment]
cc: @revgum

**Comment by revgum** [comment]
Yea, I'd ditch it.. Infact, I'll do just that!
